name: CI

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Workload Android
      run: dotnet workload install android
    - name: Workload Android AOT
      run: dotnet workload install android-aot
    - name: Build Release
      run: dotnet build --configuration Release
    - name: Test Release
      run: dotnet test --configuration Release
